version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
    - ./pydev:/pydev
    command: sh -c "python manage.py runserver 0.0.0.0:5000"
    environment: 
      - DEBUG=1