version: "3"
services:
  app:
    container_name: audio
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./pydev:/var/www/pydev
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    command:  ./entrypoint.sh