# Generated by Django 4.1.1 on 2022-09-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_doctoaudio_langue_pdf_delete_audio_delete_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfToAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.pdf')),
            ],
        ),
        migrations.DeleteModel(
            name='DocToAudio',
        ),
    ]
