# Generated by Django 4.1.1 on 2022-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pdftoaudio_delete_doctoaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='static/media/pdf'),
        ),
    ]
