# Generated by Django 4.1.1 on 2022-09-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_pdf_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='langue',
            name='code',
            field=models.CharField(default='fr', max_length=300),
        ),
    ]
