# Generated by Django 4.1.1 on 2022-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_pdftoaudio_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftoaudio',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
