# Generated by Django 4.1.1 on 2022-09-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_pdftoaudio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
